version: "3"
services:
  grpc:
    build:
      context: ./server
      dockerfile: cmd/grpc/Dockerfile
  gateway:
    build:
      context: ./server
      dockerfile: cmd/gateway/Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - grpc
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - gateway
  networks: 
